export enum SpecializedFieldType {
  HARDWARE = "HARDWARE",
  SOFTWARE = 'SOFTWARE',
  NETWORKING = 'NETWORKING',
  DATABASE = 'DATABASE',
  SECURITY = 'SECURITY',
  SYSTEM_ADMINISTRATION = 'SYSTEM_ADMINISTRATION',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT'
}
